version: '3.9'

services:
    app:
        build: 
            context: node
        container_name: app
        networks: 
            - ce-network
        tty: true
        ports: 
            - '3000:3000'
        depends_on: 
            db:
                condition: service_healthy
        
    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true        
        networks: 
            - ce-network
        ports: 
            - '3307:3306'
        volumes: 
            - "./mysql/1_schema.sql:/docker-entrypoint-initdb.d/1.sql"
            - "./mysql/2_data.sql:/docker-entrypoint-initdb.d/2.sql"
        environment: 
            - MYSQL_DATABASE=mydb
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_TCP_PORT=3307
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3307"]
            interval: 10s
            timeout: 10s
            retries: 10
            
    server:
        build: 
          context: ./nginx
        container_name: server
        ports:
          - "8080:80"
        depends_on: 
          - db
          - app
        networks: 
          - ce-network
                    
        
networks:
    ce-network:
        driver: bridge